# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d85d100b04ab79c17ade6a8b9421f586106b100ca9681b5fd098a3d9d79236d1212075f628d33fc87d0ef467adf0cb75cb9cef142afc91b8866f8844ef4100f

test:
  secret_key_base: b8bbf4452435c5e35d2bd186f107b2a20a6dc3d5355ef8ca614af98d9a50e1fccd7ac75952301876547cb5448d58e804c51c50e074dcbc4cd40a91b5dbae679c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
